# Generated by Django 4.1.6 on 2023-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('maNV', models.AutoField(primary_key=True, serialize=False)),
                ('hoNV', models.CharField(max_length=10)),
                ('tenNV', models.CharField(max_length=10)),
                ('sdt', models.IntegerField(default=0)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('diaChi', models.CharField(max_length=50)),
            ],
        ),
    ]
