# Generated by Django 4.1.6 on 2023-03-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('maGH', models.AutoField(primary_key=True, serialize=False)),
                ('trangThai', models.BooleanField(default=True)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='CTGioHang',
            fields=[
                ('maCTGH', models.AutoField(primary_key=True, serialize=False)),
                ('giaMon', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('size', models.CharField(blank=True, max_length=2)),
                ('soLuong', models.IntegerField(default=1)),
                ('maGH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.giohang')),
                ('maMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mon')),
            ],
        ),
    ]
