# Generated by Django 4.1.6 on 2023-03-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTGia',
            fields=[
                ('maGia', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(default='L', max_length=2)),
                ('giaSize', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Danhmuc',
            fields=[
                ('maDM', models.AutoField(primary_key=True, serialize=False)),
                ('tenDM', models.CharField(max_length=15)),
                ('hinhAnhDM', models.ImageField(default=None, null=True, upload_to='dm')),
                ('ngayCN', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('maMon', models.AutoField(primary_key=True, serialize=False)),
                ('tenMon', models.TextField(max_length=50)),
                ('hinhAnh', models.ImageField(default=None, upload_to='img')),
                ('moTa', models.CharField(max_length=500)),
                ('ngayCN', models.DateTimeField(auto_now_add=True)),
                ('gia', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('trangThaiMon', models.BooleanField(default=True)),
                ('maDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.danhmuc')),
                ('sizeMon', models.ManyToManyField(blank=True, to='product.ctgia')),
            ],
        ),
        migrations.CreateModel(
            name='CTDanhGia',
            fields=[
                ('idDanhGia', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0)),
                ('ngayDanhGia', models.DateTimeField(auto_now_add=True)),
                ('nhanXet', models.TextField(max_length=1000)),
                ('hinhAnh', models.ImageField(blank=True, default=None, upload_to='img')),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
                ('maMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mon')),
            ],
        ),
    ]
