# Generated by Django 4.1.6 on 2023-03-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('maKM', models.AutoField(primary_key=True, serialize=False)),
                ('tenKM', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('phantramKM', models.IntegerField(default=1)),
                ('ngayHetHan', models.DateField()),
                ('trangThai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('maTT', models.AutoField(primary_key=True, serialize=False)),
                ('tenTT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('maDH', models.AutoField(primary_key=True, serialize=False)),
                ('tongTien', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('ngayLap', models.DateTimeField(auto_now_add=True)),
                ('trangThaiDH', models.CharField(choices=[('0', 'Hủy'), ('1', 'Chưa xác nhận'), ('2', 'Đã xác nhận'), ('3', 'Đang chuẩn bị'), ('4', 'Đang vận chuyển'), ('5', 'Hoàn thành')], default=1, max_length=50)),
                ('diachi', models.CharField(blank=True, max_length=200, null=True)),
                ('sdt', models.CharField(blank=True, max_length=50, null=True)),
                ('hoten', models.CharField(blank=True, max_length=50, null=True)),
                ('maKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
                ('maKM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.khuyenmai')),
                ('maTT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.thanhtoan')),
            ],
        ),
        migrations.CreateModel(
            name='CTDonHang',
            fields=[
                ('maCTDH', models.AutoField(primary_key=True, serialize=False)),
                ('giaMon', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('soLuong', models.IntegerField(default=1)),
                ('maDH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.donhang')),
                ('maMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mon')),
            ],
        ),
    ]
